set(_CATKIN_CURRENT_PACKAGE "source_localization")
set(source_localization_VERSION "0.3.4")
set(source_localization_MAINTAINER "Jack Borer <jackborer@utexas.edu>")
set(source_localization_PACKAGE_FORMAT "1")
set(source_localization_BUILD_DEPENDS "roslaunch")
set(source_localization_BUILD_EXPORT_DEPENDS )
set(source_localization_BUILDTOOL_DEPENDS "catkin")
set(source_localization_BUILDTOOL_EXPORT_DEPENDS )
set(source_localization_EXEC_DEPENDS )
set(source_localization_RUN_DEPENDS )
set(source_localization_TEST_DEPENDS )
set(source_localization_DOC_DEPENDS )
set(source_localization_URL_WEBSITE "")
set(source_localization_URL_BUGTRACKER "")
set(source_localization_URL_REPOSITORY "")
set(source_localization_DEPRECATED "")