# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/AgeOfCorrections.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/BaselineEcef.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/BaselineHeading.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/BaselineNed.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/BasePosEcef.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/BasePosLlh.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/DeviceMonitor_V2_3_15.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/Dops.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/DopsMulti.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/GpsTime.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/GpsTimeMulti.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/Heartbeat.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/ImuAuxMulti.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/ImuRawMulti.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/InfoWifiCorrections.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/Log.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/MagRaw.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/MeasurementState_V2_4_1.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/Observation.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/PosEcef.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/PosLlh.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/PosLlhMulti.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/ReceiverState.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/ReceiverState_V2_2_15.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/ReceiverState_V2_3_15.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/ReceiverState_V2_4_1.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/TrackingState.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/TrackingState_V2_2_15.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/TrackingState_V2_3_15.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/UartState.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/UartState_V2_3_15.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/UtcTimeMulti.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/VelEcef.msg;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg/VelNed.msg"
services_str = "/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/srv/SettingsWrite.srv;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/srv/SettingsReadReq.srv;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/srv/SettingsReadResp.srv"
pkg_name = "piksi_rtk_msgs"
dependencies_str = "std_msgs;geometry_msgs;sensor_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "piksi_rtk_msgs;/home/jacksubuntu/philbart_ws/src/ethz_piksi_ros/piksi_rtk_msgs/msg;std_msgs;/opt/ros/kinetic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/kinetic/share/geometry_msgs/cmake/../msg;sensor_msgs;/opt/ros/kinetic/share/sensor_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
